shared:
    image: node:14
    settings:
        slack:
          channels:
           - 'sd-build-bot-test'
          statuses:
           - SUCCESS
           - FAILURE
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
              - echo: echo hi