shared:
  image: node:14
  settings:
    slack:
      channels:
        - sd-build-bot-test
      statuses:
        - SUCCESS
        - FAILURE
        - QUEUED
        - RUNNING
      minimized: false
jobs:
  main:
    requires: [ ~pr, ~commit ]
    steps:
      - echo hi