shared:
  image: node:14
  settings:
    slack:
      channels:
        - sd-build-bot-test
      statuses:
        - SUCCESS
        - FAILURE
jobs:
  main:
    annotations:
      screwdriver.cd/buildPeriodically: H(40-41) * * * *
    requires: [ ~pr, ~commit ]
    steps:
      - echo hi
